# converting Disqus:
#library(tidyverse)
#library(stringr)
#comments <- read_csv("~/Downloads/datascienceish-2017-06-09T22-20-06.652937-links.csv", col_names = "url1") %>%
#    filter(str_detect(url1, "\\/$")) %>%
#    mutate(url2 = str_to_lower(url1),
#           url2 = str_replace_all(url2, "http://julia", "https://julia"))
#write_csv(comments, "~/Desktop/url_mapping.csv")

baseurl = "https://juliasilge.com/"
languageCode = "en-us"
title = "Julia Silge"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
enableEmoji = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Julia Silge"
disqusshortname = "datascienceish"
googleAnalytics = "UA-68765210-1"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


[permalinks]
blog = "/blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A blog by Julia Silge"
copyright = "Copyright Â© 2019 Julia Silge"
logofile = "_images/illustrated_blog_avatar.png"
faviconfile = "_images/favicon.ico"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
github = "juliasilge"
#email = "you@example.com"
linkedin = "juliasilge"
twitter = "juliasilge"
social_banner = "_images/illustrated_blog_avatar.png"
posts_navigation = true

